<?php

/**
 * @file
 * Contains claims.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function claims_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the claims module.
    case 'help.page.claims':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Claims related functionality') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function claims_theme($existing, $type, $theme, $path) {
  return [
    'claim_voucher' => [
      'variables' => ['node' => NULL],
    ],
  ];
}

/**
 * Implements hook_preprocess_node().
 */
function claims_preprocess_node(&$variables) {
  $node = $variables['node'];
  $tempstore = \Drupal::service('user.private_tempstore')->get('claims');
  $partner_nid = $tempstore->get('partner');

  $display_options = [
    'label' => 'hidden'
  ];

  if ($partner_nid && $node->getType() == 'partners') {
    if ($node->field_barcode_image && $node->field_barcode_image->entity) {
      $variables['voucher_image'] = $node->field_barcode_image->view($display_options);
    }
    else {
      $tempstore = \Drupal::service('user.private_tempstore')->get('claims');
      $variables['voucher_code'] = $tempstore->get('voucher_code');
      \Drupal::logger('claims_preprocess_node')->notice('<pre>@type</pre>', array('@type' => print_r($tempstore->get('voucher_code'), TRUE)));
    }
  }
}

/**
 * Implementation of computed field hook for voucher code.
 */
function computed_field_field_voucher_code_compute($entity_type_manager, $entity, $fields, $delta) {
  $nid = $entity->id();
  $connection = \Drupal::database();

  $query = $connection->query('SELECT voucher_code FROM {claim_codes} WHERE partner = :nid AND used = 0 LIMIT 1', [':nid' => $nid]);
  $value = $query->fetchField();

  return $value;
}
